/**
 * Static synonym / abbreviation dictionary used by the query optimizer for
 * expansion when no AI key is configured (graceful degradation), and as a
 * fast-path supplement even when AI rewriting is available.
 */
export const SYNONYM_DICT: Record<string, string[]> = {
  ai: ['artificial intelligence', 'machine learning'],
  ml: ['machine learning'],
  ui: ['user interface'],
  ux: ['user experience'],
  api: ['application programming interface', 'endpoint'],
  db: ['database'],
  auth: ['authentication', 'authorization'],
  config: ['configuration', 'settings'],
  perf: ['performance'],
  bug: ['defect', 'issue', 'error'],
  error: ['exception', 'failure', 'issue'],
  issue: ['problem', 'bug', 'error'],
  fast: ['quick', 'rapid', 'speedy'],
  slow: ['sluggish', 'delayed', 'lagging'],
  doc: ['document', 'documentation'],
  docs: ['documents', 'documentation'],
  app: ['application'],
  info: ['information'],
  msg: ['message'],
  req: ['request'],
  res: ['response'],
  refund: ['reimbursement', 'money back'],
  policy: ['guideline', 'rule', 'terms'],
  revenue: ['income', 'earnings', 'sales'],
  customer: ['client', 'user'],
  feedback: ['review', 'comment', 'response'],
  growth: ['increase', 'expansion'],
  decline: ['decrease', 'drop', 'reduction'],
  security: ['protection', 'safety'],
  privacy: ['confidentiality', 'data protection'],
  contract: ['agreement', 'terms'],
  deadline: ['due date', 'timeline'],
  meeting: ['call', 'discussion', 'sync'],
  report: ['summary', 'analysis'],
  update: ['change', 'modification', 'revision'],
  delay: ['postponement', 'setback'],
  risk: ['hazard', 'threat', 'exposure'],
  cost: ['price', 'expense', 'expenditure'],
  profit: ['earnings', 'gain', 'margin'],
  staff: ['employees', 'personnel', 'team'],
  handeling: ['handling'],
  recieve: ['receive'],
  seperate: ['separate'],
  occured: ['occurred'],
  definately: ['definitely'],
  enviroment: ['environment'],
  managment: ['management'],
};

/**
 * Common misspelling -> correction map (used for fast "did you mean").
 */
export const COMMON_CORRECTIONS: Record<string, string> = {
  eror: 'error',
  recieve: 'receive',
  seperate: 'separate',
  occured: 'occurred',
  definately: 'definitely',
  enviroment: 'environment',
  managment: 'management',
  handeling: 'handling',
  acommodate: 'accommodate',
  begining: 'beginning',
  belive: 'believe',
  calender: 'calendar',
  comming: 'coming',
  freind: 'friend',
  goverment: 'government',
  immediatly: 'immediately',
  neccessary: 'necessary',
  noticable: 'noticeable',
  occassion: 'occasion',
  reccommend: 'recommend',
  succesful: 'successful',
  tommorow: 'tomorrow',
  untill: 'until',
  wich: 'which',
};
